### ISSUE TITLE
Clicking blank square in GUI menus produces console error

### ISSUE THREAD

**Issue by lukeeexd** [Sidpatchy/InventoryRollback-Continued#10]
Plugin Version: 1.5.3

Minecraft Version: 1.18.1

Spigot/CraftBukkit version: git-Purpur-1443 (MC: 1.18.1) 

## Expected Behavior
Clicking a blank spot in the GUI menus produces an error 

## Current Behavior
`[14:02:21 ERROR]: Could not pass event InventoryClickEvent to InventoryRollback-Continued v1.5.3
java.lang.NullPointerException: ItemStack can't be null/Air!
        at de.tr7zw.nbtapi.NBTItem.<init>(NBTItem.java:42) ~[item-nbt-api-plugin-2.9.0-SNAPSHOT.jar:?]
        at de.tr7zw.nbtapi.NBTItem.<init>(NBTItem.java:28) ~[item-nbt-api-plugin-2.9.0-SNAPSHOT.jar:?]
        at me.danjono.inventoryrollback.listeners.ClickGUI.rollbackMenu(ClickGUI.java:117) ~[InventoryRollback-Continued-1.5.3.jar:?]
        at me.danjono.inventoryrollback.listeners.ClickGUI.onInventoryClick(ClickGUI.java:83) ~[InventoryRollback-Continued-1.5.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor73.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1443]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2901) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:13) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1443]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1437) ~[purpur-1.18.1.jar:git-Purpur-1443]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1443]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1415) ~[purpur-1.18.1.jar:git-Purpur-1443]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1408) ~[purpur-1.18.1.jar:git-Purpur-1443]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1386) ~[purpur-1.18.1.jar:git-Purpur-1443]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1292) ~[purpur-1.18.1.jar:git-Purpur-1443]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1443]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

## Steps to Reproduce

1. /ir restore
2. click someone 
3. click blank area
4. error

**Comment by Sidpatchy** [comment]
Thanks for the report! Sorry it took so long for me to get around to fixing.
